
services:
  nagios:
    image: jasonrivers/nagios
    container_name: nagios_container
    ports:
      - "8080:80"
      - "5666:5666"
    networks:
      - custom_network
networks:
  custom_network:
    name: santuy
    external: true


